<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>Dramaturge.TUnit</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" Version="1.72.16" />
    <PackageReference Include="coverlet.MTP" Version="10.0.1" />
    <PackageReference Include="PinchHitter" Version="0.0.20" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="../Dramaturge.Tests/TestUtilities/FakeBrowserServer.cs;../Dramaturge.Tests/TestUtilities/FakeContext.cs;../Dramaturge.Tests/TestUtilities/FakeRemoteEnd.cs;../Dramaturge.Tests/TestUtilities/FakeResponse.cs;../Dramaturge.Tests/TestUtilities/FakeSession.cs" Link="TestUtilities/%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Dramaturge.TUnit\Dramaturge.TUnit.csproj" />
  </ItemGroup>

</Project>
