<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>Dramaturge.TUnit</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" Version="1.72.16" />
    <PackageReference Include="coverlet.MTP" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Dramaturge.TUnit\Dramaturge.TUnit.csproj" />
    <ProjectReference Include="..\Dramaturge.TestUtilities\Dramaturge.TestUtilities.csproj" />
  </ItemGroup>

</Project>
