<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>Dramaturge.NUnit</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <EnableNUnitRunner>true</EnableNUnitRunner>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NUnit" Version="5.0.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.3.0" />
    <PackageReference Include="coverlet.MTP" Version="10.0.1" />
    <PackageReference Include="PinchHitter" Version="0.0.20" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="../Dramaturge.Tests/TestUtilities/FakeBrowserServer.cs;../Dramaturge.Tests/TestUtilities/FakeContext.cs;../Dramaturge.Tests/TestUtilities/FakeRemoteEnd.cs;../Dramaturge.Tests/TestUtilities/FakeResponse.cs;../Dramaturge.Tests/TestUtilities/FakeSession.cs" Link="TestUtilities/%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Dramaturge.NUnit\Dramaturge.NUnit.csproj" />
  </ItemGroup>

</Project>
