# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          9.0.x
          10.0.x
    - name: Create Local Browser Directory
      run: mkdir -p $GITHUB_WORKSPACE/browsers
    - name: Install Firefox Nightly
      run: |
        curl -s -L -o firefox-nightly.tar.xz "https://download.mozilla.org/?product=firefox-nightly-latest-ssl&os=linux64&lang=en-US" 
        tar xJf firefox-nightly.tar.xz -C $GITHUB_WORKSPACE/browsers
    - name: Install Chrome for Testing Canary
      run: |
        curl -s -L "https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json" | jq '.channels["Canary"]["downloads"]["chrome"].[] | select(.platform == "linux64") | .url' | xargs curl -s -L -o chrome-canary.zip
        unzip chrome-canary.zip -d $GITHUB_WORKSPACE/browsers
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test Library
      run: dotnet test test/WebDriverBiDi.Tests --no-build --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=lcov -p:CoverletOutput=../coverage/lcov
      env:
        FIREFOX_EXECUTABLE: ${{ github.workspace }}/browsers/firefox/firefox
        CHROME_EXECUTABLE: ${{ github.workspace }}/browsers/chrome/chrome
    - name: Test Roslyn Analyzers
      run: dotnet test test/WebDriverBiDi.Analyzers.Tests --no-build --verbosity normal
    - name: Test Structured Logging Library
      run: dotnet test test/WebDriverBiDi.Logging.Tests --no-build --verbosity normal
    - name: Upload code coverage
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./test/coverage/lcov.info
